### ISSUE TITLE
Failed to find ' com.skocken:efficientadapter.lib:1.2.+'

### ISSUE THREAD

**Issue by Wolftein** [StanKocken/EfficientAdapter#10]
I'm getting "Failed to find: com.skocken:efficientadapter.lib:1.2.+" since last commit, 1.1+ is working fine.

**Comment by Wolftein** [comment]
Using 'com.skocken:efficientadapter.lib:1.2.0' works.

**Comment by StanKocken** [comment]
I don't have this issue on my side, it's working well even with "compile 'com.skocken:efficientadapter.lib:1.2.+'".
Are you sure it's not a configuration issue on your side (gradle offline for example)?

**Comment by Wolftein** [comment]
Yes it was due to Android Studio's cache :).
