### ISSUE TITLE
Sending References to the Holder

### ISSUE THREAD

**Issue by Rohail** [StanKocken/EfficientAdapter#11]
How to send custom objects to holder e.g reference to my Fragment object so that i can call public methods from within the Holder, any way to achieve that ?
Sorry for the inconvenience :(

**Comment by StanKocken** [comment]
It's not a good way to reference your Fragment within your Holder.
You have many way to call method of your Fragment from the Holder. For example you can call "getContext()" from the Holder to get your Activity that contains your Fragment, then call your Fragment from this Activity.

**Comment by Rohail** [comment]
hmm Ok, thanks for the quick reply, gonna go do just that
:+1:
