### ISSUE TITLE
get the position of a View

### ISSUE THREAD

**Issue by nitrico** [StanKocken/EfficientAdapter#12]
Is it possible that this adapter "breaks" the RecyclerView.LayoutManager.getPosition(View view) ?  It is always returning -1. Maybe I'm not doing it correctly but I think I am.

**Comment by StanKocken** [comment]
Just tested and no, I'm able to retrieve the correct position on my side.

    mRecyclerView.getLayoutManager().getPosition(mRecyclerView.getChildAt(0)) == 0
    mRecyclerView.getLayoutManager().getPosition(mRecyclerView.getChildAt(1)) == 1

Did you try with the method:

    mRecyclerView.getChildPosition(mRecyclerView.getChildAt(0)) ?

It should return the same thing.

**Comment by nitrico** [comment]
So I must be doing something wrong somewhere else cause both method are returning me -1. By the way, is there a way to get the LayoutManager from inside a viewholder?

Thank you so much for the answer and for the library!

**Comment by StanKocken** [comment]
Sorry to hear that, I hope you will find the issue. If you want, you can test with my sample available on this repo and let me know.

I think you can get the LayoutManager from a ViewHolder, by calling the parent of "getView()" (it's your RecyclerView), then call getLayoutManager on it.
