### ISSUE TITLE
adapter.setOnItemLongClickListener Not Working

### ISSUE THREAD

**Issue by Rohail** [StanKocken/EfficientAdapter#15]
I seems that the LongClick method of the simpleAdapter is not working as it is supposed to, the simple click listener is working fine.
And is there any way to add onItemTouchListener as well on the Adapter.

Thanks in advance

**Comment by StanKocken** [comment]
"is not working as it is supposed to" can you be more explicit? You set the listener but it never be called?

Yes, I can add the onItemTouchListener as well.

**Comment by Rohail** [comment]
Yup, adapter.setOnItemLongClickListener is not being called, no matter how long i hold the touch it still calls onItemClick when the touch is removed

**Comment by StanKocken** [comment]
Which version of the code are you using? From Gradle "compile 'com.skocken:efficientadapter.lib:1.2.+'"? From the master of this repository?

I just re-tested and it seems working on my side. I will add it into my example.

**Comment by Rohail** [comment]
Must be version issue then, i implemented the click and longclick functionality from within the Holder so its working fine now, :+1:  thanks any way,
By the way is there any way to change the values of dataset provided to the Adapter from withing the holder ? e.g i change the state of a checkbox from within the holder and want to update the respective boolean value of the object so that the next the view is drawn its checked by default and my data set would reflect the change accordingly, Sorry for being a nuisance  :(

**Comment by StanKocken** [comment]
From your holder, you have access to your object (from the method param or by calling "getObject()") so you can do whatever on it. Or you want to modify an other object of the dataset?

**Comment by Rohail** [comment]
It seems i was issues due to having an old version, and weird behaviors was due to using check-boxes with checkchangelistner in the items, (solved it somehow)
Regarding the OnItemTouch Listener, I've tried implementing the touch listener inside the holder but it disrupts the scroll behavior of the recycler ( i have recycler view inside a Viewpager fragment ), any idea to implement the proper touch behavior without disrupting the horizontal and vertical scrolls ( View pager & Recycler)

**Comment by StanKocken** [comment]
I'm not sure what you're trying to do by overriding the OnItemTouch. 
If you say to Android "I want to handle the touch by myself" (with this listener), then you have to handle it by yourself. It's your responsibility to say if you want to transmit the touch event to parents or not (by return true or false).

**Comment by Rohail** [comment]
Thanks for the help, the original issue was probly due to using the older version which is working fine now
