### ISSUE TITLE
Syntactic sugar 

### ISSUE THREAD

**Issue by zhexian** [StanKocken/EfficientAdapter#18]
# how about reduce more code?
## in EfficientViewHolder Class，add the code below  

    public void setText(int viewId, String text) {
        TextView tv = findViewByIdEfficient(viewId);
        tv.setText(text);
    }

    public void setTextColor(int viewId, int textColor) {
        TextView view = findViewByIdEfficient(viewId);
        view.setTextColor(textColor);
    }

    public void setImageResource(int viewId, int resId) {
        ImageView view = findViewByIdEfficient(viewId);
        view.setImageResource(resId);
    }

    public void setVisible(int viewId, boolean visible) {
        View view = findViewByIdEfficient(viewId);
        view.setVisibility(visible ? View.VISIBLE : View.GONE);
    }

    public void setTag(int viewId, Object tag) {
        View view = findViewByIdEfficient(viewId);
        view.setTag(tag);
    }

    public void setTag(int viewId, int key, Object tag) {
        View view = findViewByIdEfficient(viewId);
        view.setTag(key, tag);
    }

    public void setOnClickListener(int viewId, View.OnClickListener listener) {
        View view = findViewByIdEfficient(viewId);
        view.setOnClickListener(listener);
    }

### before:

                    ((TextView)findViewByIdEfficient(R.id.textView_teacher_syncHomeWork_content)).setText(object.getQueContent());
            ((TextView) findViewByIdEfficient(R.id.textView_teacher_syncHomeWork_answerTime))
                    .setText("平均答题时间：" + DatetimeUtils.formatDateForClock(Convert.toInt(object.getAnswerAvgTime())));

            findViewByIdEfficient(R.id.relativeLayout_teacher_syncHomeWork_container).setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {

                    ToastUtil.shortShow(context, "点击了：" + object.getQueId());
                }
            });

## after:
            setText(R.id.textView_teacher_syncHomeWork_content, object.getQueContent());
            setText(R.id.textView_teacher_syncHomeWork_answerTime, "平均答题时间：" + DatetimeUtils.formatDateForClock(Convert.toInt(object.getAnswerAvgTime())));

            setOnClickListener(R.id.relativeLayout_teacher_syncHomeWork_container, new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    ToastUtil.shortShow(context, "点击了：" + object.getQueId());
                }
            });

### thanks to your nice project

**Comment by StanKocken** [comment]
Thanks, this is exactly what I had in my roadmap.
But instead of putting this into EfficientViewHolder, I started to create another class, ViewUtil (I'm not sure about the name yet) that take most of the method from [RemoteViews](http://developer.android.com/reference/android/widget/RemoteViews.html) as static.


So for your example, it will be:

        ViewUtil.setText(this, R.id.textView_teacher_syncHomeWork_content, object.getQueContent());
        ViewUtil.setText(this, R.id.textView_teacher_syncHomeWork_answerTime, "平均答题时间：" + DatetimeUtils.formatDateForClock(Convert.toInt(object.getAnswerAvgTime())));

        ViewUtil.setOnClickListener(this, R.id.relativeLayout_teacher_syncHomeWork_container, new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                ToastUtil.shortShow(context, "点击了：" + object.getQueId());
            }
        });

The reason of putting this into another class is simple: you're currently using "EfficientCacheView" from "EfficientAdapter" but some other projects based on this library are using it independently (like [Presentation](https://github.com/StanKocken/Presentation). Having a class with static methods will help both.

What do you think?

**Comment by zhexian** [comment]
you are right，but for me and our team ,we need a solution which easy to read and quick to write。
 so we will still use first solution

**Comment by StanKocken** [comment]
I will think about that, maybe keep my external class but add some helper method into EfficientViewHolder that do:

	public void setText(int viewId, String text) {
	    ViewUtil.setText(mCacheView, viewId, text);
	} 

So for you into your ViewHolders it will be the same (just setText(int, String)) but behind the code will be separate.

**Comment by zhexian** [comment]
ok,this will be fine

**Comment by StanKocken** [comment]
I will do that as soon as I get some free time (and I also accept PR ;) )

**Comment by zhexian** [comment]
haha，ok。
and thank you for the nice project

**Comment by zhexian** [comment]
also ，inner class EfficientViewHolder<M_StudentInfos> will throw exception;because the default constractor is not 1 argument。
in case of generate less file，we will use static inner class,like:


    public class  CustomMultiTypeAdapterClass  extends EfficientRecyclerAdapter<M_StudentInfos> {

     // some code

    static class NormalViewHolder extends EfficientViewHolder<M_StudentInfos> {

        public NormalViewHolder(View itemView) {
            super(itemView);
        }

       @Override
        protected void updateView(Context context, M_StudentInfos object) {
        }
     }
    }

**Comment by StanKocken** [comment]
I just pushed a version with your suggestions: https://github.com/StanKocken/EfficientAdapter/commit/907eeb2ca237149724dcde8b619cd80ee1827a2e

About the Inner class issue, can you open a new issue and explain me if you have a solution.
Thanks
