### ISSUE TITLE
Inner View ClickListener

### ISSUE THREAD

**Issue by zhexian** [StanKocken/EfficientAdapter#19]
setOnItemClickListener can only use in a whole row；how to bind a clickListener to a View inside a row?

**Comment by StanKocken** [comment]
"setOnItemClickListener" is only for the whole row yes.
If you want a clicklistener on a view inside a row, you can add it manually into your ViewHolder by getting the view and set it. You can get the object linked to this viewholder with "getObject()".

**Comment by zhexian** [comment]
yes ,you are right。 and here is the code for other one who confuse about this.


    public class CustomViewHolder extends EfficientViewHolder<Book> {
    private TextView textView;

    /**
     * @param itemView the root view of the view holder. This parameter cannot be null.
     * @throws NullPointerException if the view is null
     */
    public CustomViewHolder(View itemView) {
        super(itemView);
        textView = (TextView) itemView.findViewById(R.id.textView);

        textView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Log.d("测试", "点击了" + getObject().getName());
            }
        });
    }

    @Override
    protected void updateView(Context context, Book object) {
        setText(R.id.textView, object.getName());

    }
    }
