### ISSUE TITLE
Use ViewHolder as InnerClass of a Adapter

### ISSUE THREAD

**Issue by zhexian** [StanKocken/EfficientAdapter#20]
some time,we need the ViewHolder to be a innerClass of a Adapter ,incase to share the variable of it。
so here is the code we modified to support this feature。it both support single ViewHolder class or as innerClass in Adapter。

###  AdapterHelper.class

    <T extends EfficientViewHolder> EfficientViewHolder generateViewHolder(View v,
                                                                           Class<T> viewHolderClass, EfficientRecyclerAdapter adapter) {
        Constructor<?>[] constructors = viewHolderClass.getDeclaredConstructors();

        if (constructors == null)
            return null;

        for (Constructor<?> constructor : constructors) {
            Class<?>[] parameterTypes = constructor.getParameterTypes();
            if (parameterTypes == null)
                continue;

            try {
                if (parameterTypes.length == 1 && parameterTypes[0].isAssignableFrom(View.class)) {
                    Object viewHolder = constructor.newInstance(v);
                    return (EfficientViewHolder) viewHolder;
                }

                if (parameterTypes.length == 2 && parameterTypes[1].isAssignableFrom(View.class)) {
                    Object viewHolder = constructor.newInstance(adapter, v);
                    return (EfficientViewHolder) viewHolder;
                }
            } catch (Exception e) {
                Log.e("ViewHolder init error", e.getMessage());
                throw new RuntimeException(
                        "Impossible to instantiate "
                                + viewHolderClass.getSimpleName(), e);
            }
        }

        return null;
    }

###  EfficientRecyclerAdapter.class
    @Override
    public EfficientViewHolder generateViewHolder(View v, int viewType) {
        Class<? extends EfficientViewHolder> viewHolderClass = getViewHolderClass(viewType);
        if (viewHolderClass == null) {
            mBaseAdapter.throwMissingViewHolder(viewType);
            return null;
        }
        return mBaseAdapter.generateViewHolder(v, viewHolderClass, this);
    }

**Comment by StanKocken** [comment]
I'm not sure how this code can help you to have an ViewHolder inner of an adapter.
If your call is just to have access to the adapter within your EfficientViewHolder, why don't override the method "generateViewHolder" and call a method "setAdapter" into?

**Comment by zhexian** [comment]
### example ViewHolder

    public class StudentHomeWorkBaseViewHolder extends EfficientViewHolder<M_StudentInfos> {

    protected LikeTextView mLikeTextView;

    public StudentHomeWorkBaseViewHolder(View itemView) {
        super(itemView);
        mLikeTextView = findViewByIdEfficient(R.id.teacherStudentHomeWork_like);
    }

    @Override
    protected void updateView(Context context, final M_StudentInfos object) {
     }
     }

###  if you put ViewHolder inside a Adapter ,the constructor is auto modified by the Adapter privately like this，the first paramater is the outter Adapter self

    public StudentHomeWorkBaseViewHolder(Adapter adapter,View itemView) {
        super(itemView);
        mLikeTextView = findViewByIdEfficient(R.id.teacherStudentHomeWork_like);
    }

### so that's is why we add the code below to make it work。the  parameterTypes[0] is the adpater,
      if (parameterTypes.length == 2 && parameterTypes[1].isAssignableFrom(View.class)) {
                Object viewHolder = constructor.newInstance(adapter, v);
                return (EfficientViewHolder) viewHolder;
            }

**Comment by zhexian** [comment]
If your call is just to have access to the adapter within your EfficientViewHolder, why don't override the method "generateViewHolder" and call a method "setAdapter" into?

good question. we have consider this method,two reason not use it
###1: we want easy to write viewHolder,just like a inner class can share outter class;frameWork should do this work.
###2: add this feature to improve the range of ViewHolder exist type is fine

**Comment by StanKocken** [comment]
Ok I got your point, thanks. Make sense.

Any reason you're using an inner class over a static-nested class? You need an access to the adapter within your ViewHolder?

**Comment by zhexian** [comment]
because in our project, some time  the information is satisfy by the model provided;so we need a link to adapter

**Comment by StanKocken** [comment]
Ok, I would avoid using an inner class for that but I got your point and agree that many developers would love to have this fix.

I will work on that (or you can still open a PR, so you will be an official contributor of the project ;) ) but will change few stuffs:
- Into "AdapterHelper" I don't want any reference to EfficientRecyclerAdapter, I prefer the generic EfficientAdapter (so it will work with EfficientPagerAdapter as well)
- Add the test for the first parameter to be sure it is EfficientAdapter instance into "(parameterTypes.length == 2 && parameterTypes[1].isAssignableFrom(View.class))"
- Add an exception instead of the "return null" to be sure the developer understand why we were not able to generate the ViewHolder.

Thanks again for your contribution

**Comment by xiaobaDev** [comment]
i am zheXian，thanks for inviting；once i totaly read the project,i will join it.

i also change the sequence of isAssignableFrom() ,because this method is used to check whether the paramater is  the subClass of the Object.

    String.class.isAssignableFrom(Object.class)  ----> false
    Object.class.isAssignableFrom(String.class) -----> true

### here's the code

    <T extends EfficientViewHolder> EfficientViewHolder generateViewHolder(View v,
                                                                           Class<T> viewHolderClass, EfficientAdapter adapter) {
        Constructor<?>[] constructors = viewHolderClass.getDeclaredConstructors();

        if (constructors == null)
            return null;

        for (Constructor<?> constructor : constructors) {
            Class<?>[] parameterTypes = constructor.getParameterTypes();
            if (parameterTypes == null)
                continue;

            try {
                if (parameterTypes.length == 1 && parameterTypes[0].isAssignableFrom(View.class)) {
                    Object viewHolder = constructor.newInstance(v);
                    return (EfficientViewHolder) viewHolder;
                }

                if (parameterTypes.length == 2 && EfficientAdapter.class.isAssignableFrom(parameterTypes[0]) && View.class.isAssignableFrom(parameterTypes[1])) {
                    Object viewHolder = constructor.newInstance(adapter, v);
                    return (EfficientViewHolder) viewHolder;
                }
            } catch (Exception e) {
                Log.e("ViewHolder init error", e.getMessage());
                throw new RuntimeException(
                        "Impossible to instantiate "
                                + viewHolderClass.getSimpleName(), e);
            }
        }

        throw new IllegalArgumentException(
                "Impossible to found a constructor with a view for "
                        + viewHolderClass.getSimpleName());
    }

**Comment by zhexian** [comment]
support for viewHolder in adapter is added in pr #22
